# Generated by Django 3.2 on 2021-05-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0012_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论内容', verbose_name='评论内容')),
                ('create_time', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.BooleanField(default=1, help_text='是否显示, 0-不显示，1-显示', max_length=1, verbose_name='是否显示')),
                ('article', models.ForeignKey(help_text='文章', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='文章')),
                ('author', models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'db_table': 'resource_comments',
            },
        ),
    ]
