# Generated by Django 3.2 on 2021-05-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210519_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='resource_category',
        ),
    ]
