# Generated by Django 3.2 on 2021-05-19 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210519_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称', max_length=50, verbose_name='分类名称')),
                ('create_time', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('status', models.BooleanField(default=1, help_text='是否显示, 0-不显示，1-显示', max_length=1, verbose_name='是否显示')),
            ],
            options={
                'db_table': 'resource_category',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.category', verbose_name='分类'),
        ),
    ]
