# Generated by Django 3.2 on 2021-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20210519_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, help_text='标题', max_length=50, verbose_name='标题'),
        ),
    ]
