# Generated by Django 3.2 on 2021-05-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='标签内容', max_length=20, verbose_name='标签内容')),
                ('create_time', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('status', models.BooleanField(default=1, help_text='是否显示, 0-不显示，1-显示', max_length=1, verbose_name='是否显示')),
            ],
            options={
                'db_table': 'resource_tag',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='标签', related_name='articles', to='article.Tag', verbose_name='标签'),
        ),
    ]
