# Generated by Django 3.2 on 2021-05-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_tag_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(help_text='图像内容', upload_to='avatar/%Y%m%d', verbose_name='图像内容')),
                ('create_time', models.DateField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('status', models.BooleanField(default=1, help_text='是否显示, 0-不显示，1-显示', max_length=1, verbose_name='是否显示')),
            ],
            options={
                'db_table': 'resource_avatar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='标题图', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.avatar', verbose_name='标题图'),
        ),
    ]
