# Generated by Django 3.2 on 2021-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20210521_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='文章内容', verbose_name='文章内容'),
        ),
    ]
