# Generated by Django 3.2 on 2021-05-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_content'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='avatar',
            table='resource_avatars',
        ),
        migrations.AlterModelTable(
            name='category',
            table='resource_categorys',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='resource_tags',
        ),
    ]
